### ISSUE TITLE
build failed go v1.13.7

### ISSUE THREAD

**Issue by jjhesk** [ChainSafe/go-schnorrkel#17]
this [line](https://github.com/ChainSafe/go-schnorrkel/blob/master/helpers.go#L22) please double check with go v1.13.7+

# github.com/ChainSafe/go-schnorrkel
../../../go/pkg/mod/github.com/!chain!safe/go-schnorrkel@v0.0.0-20200405005733-88cbf1b4c40d/helpers.go:22:18: syntax error: unexpected b00000111 at end of statement
note: module requires Go 1.13

**Comment by jjhesk** [comment]
go: downloading golang.org/x/crypto v0.0.0-20191206172530-e9b2fee46413
go: downloading github.com/gtank/merlin v0.1.1-0.20191105220539-8318aed1a79f
go: downloading github.com/davecgh/go-spew v1.1.0
go: downloading golang.org/x/sys v0.0.0-20190412213103-97732733099d
# github.com/ChainSafe/go-schnorrkel [github.com/ChainSafe/go-schnorrkel.test]
./helpers.go:22:18: syntax error: unexpected b00000111 at end of statement
note: module requires Go 1.13FAIL	github.com/ChainSafe/go-schnorrkel [build failed]

**Comment by jjhesk** [comment]
According to the [ascii table](https://www.techsystemsembedded.com/ascii_table.php) that `0B00000111` is also representing in `0x07` in hex. We can switch it to hex instead. I dont know why it has error for this presentation now.

**Comment by noot** [comment]
I haven't seen this problem with go1.13 or 1.14 so I'm not sure why that's happening. I've opened a PR to change it to hex: #18
