### ISSUE TITLE
Can't compile lib because of gopkg.in

### ISSUE THREAD

**Issue by leonardocustodio** [ChainSafe/go-schnorrkel#55]
We are constantly having issues with compiling this lib because of the dependency gopkg.in/yaml.v2
Can we replace it with a github link? The gopkg.in website is always having issues.

`#0 12.76 go: gopkg.in/yaml.v2@v2.2.2: unrecognized import path "gopkg.in/yaml.v2" (parse https://gopkg.in/yaml.v2?go-get=1: no go-import meta tags ())`

**Comment by noot** [comment]
@leonardocustodio how are you comping the project and what go version are you using? It appears to work fine for me, if you have a repo or other info I can use to reproduce the issue, that would be really helpful.

Also, the github `go-yaml/yaml` appears to be a mirror of what's on gopkg, so getting the module from the github link gives an error, so I'm a bit hesistant to change it:
```
$ go get github.com/go-yaml/yaml/v2@v2.2.2
go: downloading github.com/go-yaml/yaml/v2 v2.2.2
go: github.com/go-yaml/yaml/v2@v2.2.2: parsing go.mod:
	module declares its path as: gopkg.in/yaml.v2
	        but was required as: github.com/go-yaml/yaml/v2
```

Either way, can you try this branch (https://github.com/ChainSafe/go-schnorrkel/pull/56) and let me know if it works?

**Comment by leonardocustodio** [comment]
I'm using this lib https://github.com/gmajor-encrypt/sr25519-bindings/issues/4 - that depends on this project.
The go version that I'm using is `1.18`, is it probably fixed to the older commit? Let me update to check it out :)

**Comment by leonardocustodio** [comment]
Looks like it is back online. I was able to compile now using the same version. I reported the issue because this has happened multiple times over the past few weeks :(

**Comment by noot** [comment]
@leonardocustodio okay glad to hear it's working now! feel free to comment again if you see this happening still.
